# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.data_dictionary import DataDictionary  # noqa: F401,E501
from swagger_server import util


class DataDictionaryList(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, dictionaries: List[DataDictionary]=None):  # noqa: E501
        """DataDictionaryList - a model defined in Swagger

        :param dictionaries: The dictionaries of this DataDictionaryList.  # noqa: E501
        :type dictionaries: List[DataDictionary]
        """
        self.swagger_types = {
            'dictionaries': List[DataDictionary]
        }

        self.attribute_map = {
            'dictionaries': 'dictionaries'
        }
        self._dictionaries = dictionaries

    @classmethod
    def from_dict(cls, dikt) -> 'DataDictionaryList':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The data_dictionary_list of this DataDictionaryList.  # noqa: E501
        :rtype: DataDictionaryList
        """
        return util.deserialize_model(dikt, cls)

    @property
    def dictionaries(self) -> List[DataDictionary]:
        """Gets the dictionaries of this DataDictionaryList.


        :return: The dictionaries of this DataDictionaryList.
        :rtype: List[DataDictionary]
        """
        return self._dictionaries

    @dictionaries.setter
    def dictionaries(self, dictionaries: List[DataDictionary]):
        """Sets the dictionaries of this DataDictionaryList.


        :param dictionaries: The dictionaries of this DataDictionaryList.
        :type dictionaries: List[DataDictionary]
        """

        self._dictionaries = dictionaries
